from . import number_of_hours
from . import number_of_shifts
from . import number_of_shifts2
from . import no_shifts_overlaps
from . import number_of_persons
from . import number_of_hours_in_common
from . import all_hours_in_common
from . import number_of_shifts_in_common
from . import gather_rest_hours
from . import minimum_rest_hours
from . import wishes
from . import divide_shifts
from . import rest_hours_by_period
from . import rest_hours_on_sliding_window
from . import hours_by_period
from . import rest_hours_after_shifts
from . import one_person_by_shift
from . import number_of_hours_on_interval
from . import rest_hours_on_window
from . import floating_blank_period
from . import floating_blank_periods
from . import rest_hours_between_shifts
from . import rest_hours_between_shifts_test
from . import rest_hours
